use winit::keyboard::NamedKey;

/// Each entry is either a NamedKey or a character string
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum MappedKey {
    Named(NamedKey),
    Character(String),
}

pub static STR_TO_KEY: &[(&str, MappedKey)] = &[
    ("a", MappedKey::Character(String::new())),  // placeholder, will use lazy approach
];

// We'll use functions instead of a static since MappedKey contains String
pub fn str_to_mapped_key(s: &str) -> Option<MappedKey> {
    match s {
        "a" => Some(MappedKey::Character("a".into())),
        "b" => Some(MappedKey::Character("b".into())),
        "c" => Some(MappedKey::Character("c".into())),
        "d" => Some(MappedKey::Character("d".into())),
        "e" => Some(MappedKey::Character("e".into())),
        "f" => Some(MappedKey::Character("f".into())),
        "g" => Some(MappedKey::Character("g".into())),
        "h" => Some(MappedKey::Character("h".into())),
        "i" => Some(MappedKey::Character("i".into())),
        "j" => Some(MappedKey::Character("j".into())),
        "k" => Some(MappedKey::Character("k".into())),
        "l" => Some(MappedKey::Character("l".into())),
        "m" => Some(MappedKey::Character("m".into())),
        "n" => Some(MappedKey::Character("n".into())),
        "o" => Some(MappedKey::Character("o".into())),
        "p" => Some(MappedKey::Character("p".into())),
        "q" => Some(MappedKey::Character("q".into())),
        "r" => Some(MappedKey::Character("r".into())),
        "s" => Some(MappedKey::Character("s".into())),
        "t" => Some(MappedKey::Character("t".into())),
        "u" => Some(MappedKey::Character("u".into())),
        "v" => Some(MappedKey::Character("v".into())),
        "w" => Some(MappedKey::Character("w".into())),
        "x" => Some(MappedKey::Character("x".into())),
        "y" => Some(MappedKey::Character("y".into())),
        "z" => Some(MappedKey::Character("z".into())),
        "0" => Some(MappedKey::Character("0".into())),
        "1" => Some(MappedKey::Character("1".into())),
        "2" => Some(MappedKey::Character("2".into())),
        "3" => Some(MappedKey::Character("3".into())),
        "4" => Some(MappedKey::Character("4".into())),
        "5" => Some(MappedKey::Character("5".into())),
        "6" => Some(MappedKey::Character("6".into())),
        "7" => Some(MappedKey::Character("7".into())),
        "8" => Some(MappedKey::Character("8".into())),
        "9" => Some(MappedKey::Character("9".into())),
        "F1" => Some(MappedKey::Named(NamedKey::F1)),
        "F2" => Some(MappedKey::Named(NamedKey::F2)),
        "F3" => Some(MappedKey::Named(NamedKey::F3)),
        "F4" => Some(MappedKey::Named(NamedKey::F4)),
        "F5" => Some(MappedKey::Named(NamedKey::F5)),
        "F6" => Some(MappedKey::Named(NamedKey::F6)),
        "F7" => Some(MappedKey::Named(NamedKey::F7)),
        "F8" => Some(MappedKey::Named(NamedKey::F8)),
        "F9" => Some(MappedKey::Named(NamedKey::F9)),
        "F10" => Some(MappedKey::Named(NamedKey::F10)),
        "F11" => Some(MappedKey::Named(NamedKey::F11)),
        "F12" => Some(MappedKey::Named(NamedKey::F12)),
        "Up" => Some(MappedKey::Named(NamedKey::ArrowUp)),
        "Right" => Some(MappedKey::Named(NamedKey::ArrowRight)),
        "Down" => Some(MappedKey::Named(NamedKey::ArrowDown)),
        "Left" => Some(MappedKey::Named(NamedKey::ArrowLeft)),
        "`" => Some(MappedKey::Character("`".into())),
        "@" => Some(MappedKey::Character("@".into())),
        "*" => Some(MappedKey::Character("*".into())),
        "-" => Some(MappedKey::Character("-".into())),
        "=" => Some(MappedKey::Character("=".into())),
        "+" => Some(MappedKey::Character("+".into())),
        "[" => Some(MappedKey::Character("[".into())),
        "]" => Some(MappedKey::Character("]".into())),
        "\\" => Some(MappedKey::Character("\\".into())),
        ";" => Some(MappedKey::Character(";".into())),
        ":" => Some(MappedKey::Character(":".into())),
        "'" => Some(MappedKey::Character("'".into())),
        "," => Some(MappedKey::Character(",".into())),
        "." => Some(MappedKey::Character(".".into())),
        "/" => Some(MappedKey::Character("/".into())),
        "Escape" => Some(MappedKey::Named(NamedKey::Escape)),
        "Tab" => Some(MappedKey::Named(NamedKey::Tab)),
        "Insert" => Some(MappedKey::Named(NamedKey::Insert)),
        "Delete" => Some(MappedKey::Named(NamedKey::Delete)),
        "Backspace" => Some(MappedKey::Named(NamedKey::Backspace)),
        "Enter" => Some(MappedKey::Named(NamedKey::Enter)),
        "Home" => Some(MappedKey::Named(NamedKey::Home)),
        "End" => Some(MappedKey::Named(NamedKey::End)),
        "PageUp" => Some(MappedKey::Named(NamedKey::PageUp)),
        "PageDown" => Some(MappedKey::Named(NamedKey::PageDown)),
        "Space" => Some(MappedKey::Named(NamedKey::Space)),
        _ => None,
    }
}

pub fn mapped_key_to_str(key: &MappedKey) -> Option<&'static str> {
    match key {
        MappedKey::Character(c) => match c.as_str() {
            "a" => Some("a"), "b" => Some("b"), "c" => Some("c"), "d" => Some("d"),
            "e" => Some("e"), "f" => Some("f"), "g" => Some("g"), "h" => Some("h"),
            "i" => Some("i"), "j" => Some("j"), "k" => Some("k"), "l" => Some("l"),
            "m" => Some("m"), "n" => Some("n"), "o" => Some("o"), "p" => Some("p"),
            "q" => Some("q"), "r" => Some("r"), "s" => Some("s"), "t" => Some("t"),
            "u" => Some("u"), "v" => Some("v"), "w" => Some("w"), "x" => Some("x"),
            "y" => Some("y"), "z" => Some("z"),
            "0" => Some("0"), "1" => Some("1"), "2" => Some("2"), "3" => Some("3"),
            "4" => Some("4"), "5" => Some("5"), "6" => Some("6"), "7" => Some("7"),
            "8" => Some("8"), "9" => Some("9"),
            "`" => Some("`"), "@" => Some("@"), "*" => Some("*"), "-" => Some("-"),
            "=" => Some("="), "+" => Some("+"), "[" => Some("["), "]" => Some("]"),
            "\\" => Some("\\"), ";" => Some(";"), ":" => Some(":"), "'" => Some("'"),
            "," => Some(","), "." => Some("."), "/" => Some("/"),
            _ => None,
        },
        MappedKey::Named(named) => match named {
            NamedKey::F1 => Some("F1"), NamedKey::F2 => Some("F2"), NamedKey::F3 => Some("F3"),
            NamedKey::F4 => Some("F4"), NamedKey::F5 => Some("F5"), NamedKey::F6 => Some("F6"),
            NamedKey::F7 => Some("F7"), NamedKey::F8 => Some("F8"), NamedKey::F9 => Some("F9"),
            NamedKey::F10 => Some("F10"), NamedKey::F11 => Some("F11"), NamedKey::F12 => Some("F12"),
            NamedKey::ArrowUp => Some("Up"), NamedKey::ArrowRight => Some("Right"),
            NamedKey::ArrowDown => Some("Down"), NamedKey::ArrowLeft => Some("Left"),
            NamedKey::Escape => Some("Escape"), NamedKey::Tab => Some("Tab"),
            NamedKey::Insert => Some("Insert"), NamedKey::Delete => Some("Delete"),
            NamedKey::Backspace => Some("Backspace"), NamedKey::Enter => Some("Enter"),
            NamedKey::Home => Some("Home"), NamedKey::End => Some("End"),
            NamedKey::PageUp => Some("PageUp"), NamedKey::PageDown => Some("PageDown"),
            NamedKey::Space => Some("Space"),
            _ => None,
        },
    }
}
